import {
  BarsLoader,
  DotsLoader,
  GridLoader,
  LogoSpinLoader,
  PulseLoader,
  RingLoader,
  SpinLoader,
  TypingLoader,
  WaveLoader,
  BlobLoader,
  FlowLoader,
  RotateLoader,
  ElementLoader,
  BounceLoader,
  SkeletonLoader,
  SpinDotsLoader,
  HeatmapLoader,
  MorphLoader,
  ProgressRingLoader,
  StairLoader,
  SquaresLoader,
  RippleLoader,
  OrbitLoader,
  PlaneLoader,
  HashtagLoader,
  SnakeLoader,
} from "react-loadly";
import {
  commonProps,
  type ILoaderConfig,
  type LoaderKind,
} from "@/types/ILoaderConfig";

export const LOADER_CONFIGS: { [K in LoaderKind]: ILoaderConfig<K> } = {
  spin: {
    component: SpinLoader,
    title: "Spin Loader",
    interface: "IBaseLoaderProps",
    commonProps: commonProps,
    uniqueProps: [],
  },
  pulse: {
    component: PulseLoader,
    title: "Pulse Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth"],
  },
  wave: {
    component: WaveLoader,
    title: "Wave Loader",
    interface: "IFluidLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["fluidity", "amplitude", "secondaryColor"],
  },
  grid: {
    component: GridLoader,
    title: "Grid Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
  },
  typing: {
    component: TypingLoader,
    title: "Typing Loader",
    interface: "ITextLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["loop", "charDelay", "fontWeight", "fontFamily"],
  },
  logo: {
    component: LogoSpinLoader,
    title: "Logo Loader",
    interface: "ILogoLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["src", "alt", "animationType", "glowIntensity"],
  },
  bars: {
    component: BarsLoader,
    title: "Bars Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
  },
  dots: {
    component: DotsLoader,
    title: "Dots Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
  },
  blob: {
    component: BlobLoader,
    title: "Blob Loader",
    interface: "IFluidLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["fluidity", "amplitude", "secondaryColor"],
  },
  ring: {
    component: RingLoader,
    title: "Ring Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["borderWidth", "count"],
  },
  flow: {
    component: FlowLoader,
    title: "Flow Loader",
    interface: "IFluidLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["fluidity", "amplitude", "secondaryColor"],
  },
  rotate: {
    component: RotateLoader,
    title: "Rotate Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
  },
  element: {
    component: ElementLoader,
    title: "Element Loader",
    interface: "IElementLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["animationType", "children", "glowIntensity"],
  },
  bounce: {
    component: BounceLoader,
    title: "Bounce Loader",
    interface: "IGeometricLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
  },

  skeleton: {
    component: SkeletonLoader,
    title: "Skeleton Loader",
    interface: "ISkeletonLoaderProps",
    commonProps: commonProps,
    uniqueProps: [
      "variant",
      "shimmer",
      "shimmerColor",
      "highlightColor",
      "spacing",
      "borderRadius",
      "lines",
      "waveDirection",
      "waveWidth",
      "aria-label",
    ],
  },

  spinDots: {
    component: SpinDotsLoader,
    title: "Spin Dots Loader",
    interface: "ISpinDotsLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["dots", "gap"],
    isNew: true,
  },
  heatmap: {
    component: HeatmapLoader,
    title: "Heatmap Loader",
    interface: "IHeatmapLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["rows", "cols"],
    isNew: true,
  },
  morph: {
    component: MorphLoader,
    title: "Morph Loader",
    interface: "IMorphLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["variant", "speed"],
    isNew: true,
  },
  progressRing: {
    component: ProgressRingLoader,
    title: "Progress Ring Loader",
    interface: "IProgressRingLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["progress", "thickness", "secondaryColor"],
    isNew: true,
  },
  stair: {
    component: StairLoader,
    title: "Stair Loader",
    interface: "IStairLoaderProps",
    commonProps: commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
    isNew: true,
  },
  squares: {
    component: SquaresLoader,
    title: "Squares Loader",
    interface: "ISquaresLoaderProps",
    commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
    isNew: true,
  },

  ripple: {
    component: RippleLoader,
    title: "Ripple Loader",
    interface: "IRippleLoaderProps",
    commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
    isNew: true,
  },

  orbit: {
    component: OrbitLoader,
    title: "Orbit Loader",
    interface: "IOrbitLoaderProps",
    commonProps,
    uniqueProps: ["count", "secondaryColor", "borderWidth"],
    isNew: true,
  },

  plane: {
    component: PlaneLoader,
    title: "Plane Loader",
    interface: "IPlaneLoaderProps",
    commonProps,
    uniqueProps: ["borderWidth", "secondaryColor"],
    isNew: true,
  },

  hashtag: {
    component: HashtagLoader,
    title: "Hashtag Loader",
    interface: "IHashtagLoaderProps",
    commonProps,
    uniqueProps: ["count", "borderWidth", "secondaryColor"],
    isNew: true,
  },

  snake: {
    component: SnakeLoader,
    title: "Snake Loader",
    interface: "ISnakeLoaderProps",
    commonProps,
    uniqueProps: ["count", "secondaryColor", "borderWidth"],
    isNew: true,
  },
};
